### ISSUE TITLE
Changelog.md is not up-to-date

### ISSUE THREAD

**Issue by bagage** [fulls1z3/angular-tslint-rules#59]
Currently [changelog.md lastest version](https://github.com/fulls1z3/angular-tslint-rules/blob/master/CHANGELOG.md) is 1.14.0, but 1.20.0 was released. I'd love to see tese listed too to see what changed recently.

Thanks!

**Comment by fulls1z3** [comment]
thanks for reminding me, let's delete the changelog file which is out-of-date already.

you can see the changelog at https://github.com/fulls1z3/angular-tslint-rules/releases
